trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    Write-Host "Processor Information:"
    Get-CimInstance Win32_Processor | Select-Object Name, NumberOfCores, NumberOfLogicalProcessors
    Write-Host "Number of CPU Cores:"
    (Get-CimInstance Win32_Processor).NumberOfCores
    Write-Host "Number of Logical Processors:"
    (Get-CimInstance Win32_Processor).NumberOfLogicalProcessors
  displayName: 'Display Processor Info on Windows'
