name: Processor Info

on:
  push:
    branches:
      - main

jobs:
  processor-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display processor information
        run: |
          echo "Processor Information:"
          lscpu

      - name: Display number of cores
        run: |
          echo "Number of CPU Cores:"
          grep -c ^processor /proc/cpuinfo
