trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "==== System Information ===="
    uname -a
    echo ""
    echo "==== CPU Information ===="
    lscpu
    echo ""
    echo "==== Memory Information ===="
    free -h
    echo ""
    echo "==== Disk Space Information ===="
    df -h
    echo ""
    echo "==== GPU Information ===="
    if command -v lspci > /dev/null; then
      lspci | grep -i 'vga\|3d\|2d'
    else
      echo "lspci command not found, GPU information cannot be retrieved."
    fi
  displayName: 'Show system information'
