version: 2.1

jobs:
  system-info:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Check if 'info' file was modified and show system info
          command: |
            if git diff --name-only HEAD~1 | grep -q "^info$"; then
              echo "File 'info' was modified. Running tasks..."
              echo "==== System Information ===="
              uname -a
              echo ""
              echo "==== CPU Information ===="
              lscpu
              echo ""
              echo "==== Memory Information ===="
              free -h
              echo ""
              echo "==== Disk Space Information ===="
              df -h
            else
              echo "File 'info' was not modified. Skipping tasks."
              exit 0
            fi

workflows:
  version: 2
  system-info-workflow:
    jobs:
      - system-info
