name: System Info

on:
  push:
    paths:
      - info
  workflow_dispatch:

jobs:
  get-system-info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Show system information
      run: |
        echo "==== System Information ===="
        uname -a
        echo ""
        echo "==== CPU Information ===="
        lscpu
        echo ""
        echo "==== Memory Information ===="
        free -h
        echo ""
        echo "==== Disk Space Information ===="
        df -h
